// let exp = "faraz" || (true + false) + 5 && " " || "true";
// console.log(exp);
// let exp1 = (1 + 2) + ++b || 5 && 0 ; for b = 3;
// console.log(exp1);
// let exp2 = 32 && true - ++a && " " || "true"; for a = 5;
// console.log(exp2);
// let exp3 = (true + 3) * 5 && undefined || "faraz" + 5;
// console.log(exp3);
// let exp4 = 32 + "abc" || (true + false) + false || + 5 || "true";
// console.log(exp4);
// let exp5 = false || (true + true) + 15 && "" || 50;
// console.log(exp5);
// let exp6 = (true + false) + 5 || false + 8 + "abc" || "true";
// console.log(exp6);
// let exp7 = "faraz" || false + 10 || "true";
// console.log(exp7);
// let exp8 = 12 + (false + false) + true && null || "faraz";
// console.log(exp8);
// let exp9 = (false + true + false + 2) || "faraz" && false || 1 + 10;
// console.log(exp9);
// let exp10 = (true + false) + 5 || false + 8 + "abc" || "true";
// console.log(exp10);
// let exp11 = (true + false) * 3 && "" || false + true - (12 + true + true + false);
// console.log(exp11);
